baseURL = 'https://central-baleal.github.io/'
title = 'Central Food & Drinks'
defaultContentLanguage = 'pt'
defaultContentLanguageInSubdir = false

[languages]
  [languages.pt]
    languageName = 'PT'
    weight = 1
    title = 'Central Food & Drinks - Menu'
    [languages.pt.params]
      flag = 'ğŸ‡µğŸ‡¹'
    
  [languages.en]
    languageName = 'EN'
    weight = 2
    title = 'Central Food & Drinks - Menu'
    [languages.en.params]
      flag = 'ğŸ‡¬ğŸ‡§'

[params]
  description = 'Restaurant menu'

[markup.goldmark.renderer]
  unsafe = true
